name = "iris-tutorial"
version = "0.1.0"
defaultTargets = ["IrisTutorial"]

[[require]]
name = "iris"
git = "https://github.com/leanprover-community/iris-lean.git"
rev = "unstable"

[[lean_lib]]
name = "IrisTutorial"
